services:
  - type: web
    name: lan-game-vote
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DB_PATH
        value: /var/data/db.json
